name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  detect-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Find Rust projects
        id: find-projects
        run: |
          projects=$(find . -type f -name "Cargo.toml" -exec dirname {} \; | sort -u | jq -R -s -c 'split("\n")[:-1]')
          echo "Found projects: $projects"
          echo "projects=$projects" >> $GITHUB_OUTPUT

      - name: Build and test projects
        run: |
          projects='${{ steps.find-projects.outputs.projects }}'
          echo "$projects" | jq -c '.[]' | while read project; do
            project=$(echo $project | tr -d '"')
            echo "Building and testing $project"
            cd "$project"
            if [ -f "Cargo.lock" ]; then
              if cargo build --verbose; then
                cargo test --verbose
              else
                echo "Build failed for $project"
              fi
            else
              echo "Skipping $project (no Cargo.lock found)"
            fi
            cd - > /dev/null
          done

      - name: Report build status
        if: failure()
        run: |
          echo "Some projects failed to build or test. Please check the logs for details."