name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  detect-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Find Rust projects
        id: find-projects
        run: |
          projects=$(find . -type f -name "Cargo.toml" -exec dirname {} \; | sort -u)
          echo "Found projects: $projects"
          echo "projects=$projects" >> $GITHUB_OUTPUT

      - name: Build and test projects
        run: |
          for project in ${{ steps.find-projects.outputs.projects }}; do
            echo "Building and testing $project"
            cd "$project"
            if [ -f "Cargo.lock" ]; then
              cargo build --verbose
              cargo test --verbose
            else
              echo "Skipping $project (no Cargo.lock found)"
            fi
            cd - > /dev/null
          done